# permissions for end users to edit issues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: issue-operator
    app.kubernetes.io/managed-by: kustomize
  name: issue-editor-role
rules:
- apiGroups:
  - issues.konflux.dev
  resources:
  - issues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - issues.konflux.dev
  resources:
  - issues/status
  verbs:
  - get
