---
apiVersion: v1
kind: Namespace
metadata:
  name: team-alpha
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-beta
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-gamma
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-delta
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: failed-build-frontend
  namespace: team-alpha
spec:
  title: "Frontend build failed due to dependency conflict"
  description: "The build process for the frontend component failed because of conflicting versions of React dependencies"
  severity: major
  issueType: build
  scope:
    resourceType: component
    resourceName: frontend-ui
    resourceNamespace: team-alpha
  relatedIssues: 
    - "dependency-update-needed-frontend"
  links:
    - title: "Build Logs"
      url: "https://konflux.dev/logs/build/frontend-ui/12345"
    - title: "Fix Instructions"
      url: "https://konflux.dev/docs/fixing-dependency-conflicts"
condition:
  state: active
  detectedTimestamp: "2025-04-30T15:45:30Z"
  resolvedTimestamp: ""
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: failed-test-api
  namespace: team-alpha
spec:
  title: "API integration tests failing on database connection"
  description: "Integration tests for the API component are failing because the database connection is timing out"
  severity: critical
  issueType: test
  scope:
    resourceType: component
    resourceName: backend-api
    resourceNamespace: team-alpha
  relatedIssues: 
    - "database-connection-timeout"
  links:
    - title: "Test Logs"
      url: "https://konflux.dev/logs/test/backend-api/23456"
    - title: "Database Connection Guide"
      url: "https://konflux.dev/docs/database-connection-troubleshooting"
condition:
  state: active
  detectedTimestamp: "2025-05-01T09:15:22Z"
  resolvedTimestamp: ""
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: release-failed-production
  namespace: team-beta
spec:
  title: "Production release failed during deployment"
  description: "The production release of the e-commerce application failed during the deployment phase due to resource limits"
  severity: critical
  issueType: release
  scope:
    resourceType: application
    resourceName: e-commerce-app
    resourceNamespace: team-beta
  relatedIssues: 
    - "resource-quota-exceeded"
  links:
    - title: "Release Logs"
      url: "https://konflux.dev/logs/release/e-commerce-app/34567"
    - title: "Resource Configuration Guide"
      url: "https://konflux.dev/docs/resource-configuration"
condition:
  state: active
  detectedTimestamp: "2025-04-29T18:30:45Z"
  resolvedTimestamp: ""
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: dependency-update-needed-frontend
  namespace: team-alpha
spec:
  title: "Frontend dependency updates available"
  description: "Security vulnerabilities found in current dependencies. Updates are available and recommended."
  severity: major
  issueType: dependency
  scope:
    resourceType: component
    resourceName: frontend-ui
    resourceNamespace: team-alpha
  relatedIssues: 
    - "failed-build-frontend"
  links:
    - title: "Dependency Report"
      url: "https://konflux.dev/security/dependencies/frontend-ui/78901"
    - title: "Update Instructions"
      url: "https://konflux.dev/docs/updating-dependencies-safely"
condition:
  state: active
  detectedTimestamp: "2025-04-28T14:20:10Z"
  resolvedTimestamp: ""
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: pipeline-outdated
  namespace: team-gamma
spec:
  title: "Pipeline tasks using deprecated API versions"
  description: "Several pipeline tasks are using API versions that will be deprecated in the next Konflux update"
  severity: minor
  issueType: pipeline
  scope:
    resourceType: workspace
    resourceName: data-processing-workspace
    resourceNamespace: team-gamma
  relatedIssues: []
  links:
    - title: "Pipeline Configuration"
      url: "https://konflux.dev/pipelines/data-processing-workspace/45678"
    - title: "API Migration Guide"
      url: "https://konflux.dev/docs/api-migration-guide"
condition:
  state: active
  detectedTimestamp: "2025-04-25T11:10:30Z"
  resolvedTimestamp: ""
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: failed-pipeline-run
  namespace: team-delta
spec:
  title: "Pipeline run failed during deployment stage"
  description: "The pipeline run for the analytics service failed during the deployment stage due to insufficient permissions"
  severity: major
  issueType: pipeline
  scope:
    resourceType: pipelinerun
    resourceName: analytics-service-deploy-123
    resourceNamespace: team-delta
  relatedIssues: 
    - "permission-config-incorrect"
  links:
    - title: "Pipeline Run Logs"
      url: "https://konflux.dev/logs/pipelinerun/analytics-service-deploy-123/56789"
    - title: "Permissions Configuration Guide"
      url: "https://konflux.dev/docs/pipeline-permissions"
condition:
  state: active
  detectedTimestamp: "2025-04-30T16:45:20Z"
  resolvedTimestamp: ""
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: test-flaky-mobile
  namespace: team-alpha
spec:
  title: "Mobile app tests showing intermittent failures"
  description: "The integration tests for the mobile app component are showing intermittent failures that may be related to test environment stability"
  severity: minor
  issueType: test
  scope:
    resourceType: component
    resourceName: mobile-app
    resourceNamespace: team-alpha
  relatedIssues: []
  links:
    - title: "Test Logs"
      url: "https://konflux.dev/logs/test/mobile-app/67890"
    - title: "Test Environment Guide"
      url: "https://konflux.dev/docs/test-environment-setup"
condition:
  state: resolved
  detectedTimestamp: "2025-04-28T10:25:15Z"
  resolvedTimestamp: "2025-04-29T14:35:40Z"
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: outdated-dependency-database
  namespace: team-beta
spec:
  title: "Database client library needs security update"
  description: "The database client library used by multiple components has a critical security vulnerability that needs to be addressed"
  severity: critical
  issueType: dependency
  scope:
    resourceType: application
    resourceName: e-commerce-app
    resourceNamespace: team-beta
  relatedIssues: 
    - "database-connection-timeout"
  links:
    - title: "Security Advisory"
      url: "https://konflux.dev/security/advisories/CVE-2025-1234"
    - title: "Update Instructions"
      url: "https://konflux.dev/docs/database-library-update"
condition:
  state: resolved
  detectedTimestamp: "2025-04-25T09:20:30Z"
  resolvedTimestamp: "2025-04-30T13:40:15Z"
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: build-warning-logging
  namespace: team-gamma
spec:
  title: "Build warnings in logging component"
  description: "The logging component is generating build warnings about deprecated APIs that should be addressed"
  severity: info
  issueType: build
  scope:
    resourceType: component
    resourceName: logging-service
    resourceNamespace: team-gamma
  relatedIssues: []
  links:
    - title: "Build Logs"
      url: "https://konflux.dev/logs/build/logging-service/89012"
    - title: "API Migration Guide"
      url: "https://konflux.dev/docs/api-migration-guide"
condition:
  state: active
  detectedTimestamp: "2025-04-27T15:30:45Z"
  resolvedTimestamp: ""
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: database-connection-timeout
  namespace: team-alpha
spec:
  title: "Database connection timeouts affecting multiple components"
  description: "Database connection timeouts are occurring across multiple components, potentially due to configuration or resource constraints"
  severity: critical
  issueType: release
  scope:
    resourceType: workspace
    resourceName: main-workspace
    resourceNamespace: team-alpha
  relatedIssues: 
    - "failed-test-api"
    - "outdated-dependency-database"
  links:
    - title: "Infrastructure Logs"
      url: "https://konflux.dev/logs/infrastructure/database/90123"
    - title: "Database Scaling Guide"
      url: "https://konflux.dev/docs/database-scaling"
condition:
  state: active
  detectedTimestamp: "2025-05-01T08:10:25Z"
  resolvedTimestamp: ""
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: permission-config-incorrect
  namespace: team-delta
spec:
  title: "Incorrect permission configuration for deployment service account"
  description: "The service account used for deployments has insufficient permissions, causing pipeline failures"
  severity: major
  issueType: release
  scope:
    resourceType: application
    resourceName: analytics-service
    resourceNamespace: team-delta
  relatedIssues: 
    - "failed-pipeline-run"
  links:
    - title: "RBAC Configuration"
      url: "https://konflux.dev/config/rbac/analytics-service/12345"
    - title: "Service Account Guide"
      url: "https://konflux.dev/docs/service-account-configuration"
condition:
  state: active
  detectedTimestamp: "2025-04-30T15:30:10Z"
  resolvedTimestamp: ""
---
apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  name: resource-quota-exceeded
  namespace: team-beta
spec:
  title: "Namespace resource quota exceeded during deployment"
  description: "The namespace resource quota was exceeded during the deployment phase, causing the release to fail"
  severity: critical
  issueType: release
  scope:
    resourceType: application
    resourceName: e-commerce-app
    resourceNamespace: team-beta
  relatedIssues: 
    - "release-failed-production"
  links:
    - title: "Resource Usage Report"
      url: "https://konflux.dev/config/resources/team-beta/23456"
    - title: "Resource Planning Guide"
      url: "https://konflux.dev/docs/resource-planning"
condition:
  state: active
  detectedTimestamp: "2025-04-29T18:15:30Z"
  resolvedTimestamp: ""
---
