apiVersion: issues.konflux.dev/v1beta1
kind: Issue
metadata:
  labels:
    app.kubernetes.io/name: issue-operator
    app.kubernetes.io/managed-by: kustomize
  name: issue-sample
spec:
  # TODO(user): Add fields here
